SELECT    
kgs_crashoutput081_rloffsetintersectall_attributes.fid_kgs_crashoutput081_rloffset,    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_kgs_crashoutput081_r,    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_kgs_crashoutput081_1,    
kgs_crashoutput081_rloffsetintersectall_attributes.objectid,    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_kgs_crashoutput081_2,    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_kgs_crashoutput08_10,    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13517,    
kgs_crashoutput081_rloffsetintersectall_attributes.shape,   
kgs_crashoutput081_rloffsetintersectall_attributes.a_rd,    
kgs_crashoutput081_rloffsetintersectall_attributes.rd,    
kgs_crashoutput081_rloffsetintersectall_attributes.sts,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_sts,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_pod,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_pom,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_l_from,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_l_to,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_r_from,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_r_to,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_stp,    
kgs_crashoutput081_rloffsetintersectall_attributes.a_prd,    
kgs_crashoutput081_rloffsetintersectall_attributes.aliaslabel,    
kgs_crashoutput081_rloffsetintersectall_attributes.ngaliasid,    
kgs_crashoutput081_rloffsetintersectall_attributes.aliassegid,    
kgs_crashoutput081_rloffsetintersectall_attributes.pod,    
kgs_crashoutput081_rloffsetintersectall_attributes.spdlimit,    
kgs_crashoutput081_rloffsetintersectall_attributes.rdlabel,    
kgs_crashoutput081_rloffsetintersectall_attributes.pom,    
kgs_crashoutput081_rloffsetintersectall_attributes.prd,    
kgs_crashoutput081_rloffsetintersectall_attributes.rdsegid,    
kgs_crashoutput081_rloffsetintersectall_attributes.stp,    
kgs_crashoutput081_rloffsetintersectall_attributes.buff_dist,    
kgs_crashoutput081_rloffsetintersectall_attributes.fid_roadcenterline081rlaliasgeo,    
kgs_crashoutput081_rloffsetintersectall_attributes.orig_fid,    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13531 AS "on road name",    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13532 AS "on road type",    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13530 AS "on road prefix dir",    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13529 AS "at road direction",    
kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13528 AS "at road distance feet",   
substring(kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13531, 1, 1) AS "on road name_firstchar",   
substring(kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13531, 2, 150) AS "on road name_restchars",   
TRIM(LEADING '0' FROM substring(kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13531, 2, 150)) AS "on road name_restchars0",   
substring(kgs_crashoutput081_rloffsetintersectall_attributes.a_rd, 1, 1) AS "alias road name_firstchar",   
substring(kgs_crashoutput081_rloffsetintersectall_attributes.a_rd, 2, 150) AS "alias road name_restchars",   
TRIM(LEADING '0' FROM substring(kgs_crashoutput081_rloffsetintersectall_attributes.a_rd, 2, 150)) AS "alias road name_restchars0"    
FROM    
sde.kgs_crashoutput081_rloffsetintersectall_attributes 
WHERE 1=1 
AND substring(kgs_crashoutput081_rloffsetintersectall_attributes.a_rd, 1, 1)  = substring(kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13531, 1, 1)  
AND TRIM(LEADING '0' FROM substring(kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13531, 2, 150)) = TRIM(LEADING '0' FROM substring(kgs_crashoutput081_rloffsetintersectall_attributes.a_rd, 2, 150)) 
AND kgs_crashoutput081_rloffsetintersectall_attributes.geodev_sde_gis_gc_081rl_2_13529 = E  
